### ISSUE TITLE
请问这份代码准确率能达到多少呢？

### ISSUE THREAD

**Issue by zhongzhh8** [Yidadaa/Pytorch-Video-Classification#1]

**Comment by Yidadaa** [comment]
你好，感谢关注我的项目，本项目仅用来练手使用，由于UCF101数据集太过庞大，我并未在UCF101的大数据集上进行训练，而是从中选取了10类左右进行测试，测试准确率在80%左右。

**Comment by zhongzhh8** [comment]
> 你好，感谢关注我的项目，本项目仅用来练手使用，由于UCF101数据集太过庞大，我并未在UCF101的大数据集上进行训练，而是从中选取了10类左右进行测试，测试准确率在80%左右。

按理说resnet152参数量是非常大的，你使用了多少显存才能跑起来？我换用resnet18之后，准确率大概只有50%

**Comment by Yidadaa** [comment]
@zhongzhh8 

我是用了 pytorch 预训练的 resnet152，然后在训练时锁定了 resnet152 部分的参数，只训练 rnn 部分的参数，可以看这里：https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/model.py#L50

这样就避免了训练时 resnet152 部分的参数更新，从而节省显存。

其实 UCF101 数据集的场景差别很大，CNN + LSTM 的架构就能达到 80%+ 的准确度（数据来源：https://github.com/BoPang1996/Deep-RNN-Framework#action-recognition-and-anticipation ），引入光流等信息基本可以稳上 90%。

你使用 resnet18 准确度上不去的原因，我觉得应该是没有使用预训练参数，你可以试着使用 resnet18 在 imagenet 上的预训练权重接着训练，效果应该会好很多。

**Comment by Yidadaa** [comment]
对了，补充下训练时的显存占用，`batch_size = 128`时单卡 24GB 显存没占满，用了大概 20G。

**Comment by zhongzhh8** [comment]
谢谢你的回复。我之前是用的resnet18预训练+finetune在全数据集上跑出来的50%准确率。然后我换成resnet152+固定参数后，跑的很慢。我主要想做的其实是视频检索，改成视频检索后效果很差，map只有0.1，估计resnet152+LSTM是没戏了，目前我打算改用一下其他模型了。
总之还是多谢你的意见了。

**Comment by Yidadaa** [comment]
@zhongzhh8 

加油嗷铁汁，祝早日出成果。

**Comment by Zhangzhiwei1995** [comment]
我用你的网络训练UCF101的时候出现了这样的问题 好像是download出现了问题
RuntimeError: Couldn't open shared file mapping: error code: <1455>
能加qq请教下吗 1069842319

**Comment by Yidadaa** [comment]
@Zhangzhiwei1995 

在 github 讨论吧，这样可以帮助到更多的人，建议把完整的报错信息贴上来。

**Comment by Zhangzhiwei1995** [comment]
好的   谢谢




------------------ 原始邮件 ------------------
发件人: "Yifei Zhang"<notifications@github.com>;
发送时间: 2019年10月15日(星期二) 下午3:05
收件人: "Yidadaa/Pytorch-Video-Classification"<Pytorch-Video-Classification@noreply.github.com>;
抄送: "≮訫@煉冷≯"<1069842319@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Yidadaa/Pytorch-Video-Classification] 请问这份代码准确率能达到多少呢？ (#1)




@Zhangzhiwei1995
 
在 github 讨论吧，这样可以帮助到更多的人，建议把完整的报错信息贴上来。

**Comment by Zhangzhiwei1995** [comment]
> 好的 谢谢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Yifei Zhang"<notifications@github.com>; 发送时间: 2019年10月15日(星期二) 下午3:05 收件人: "Yidadaa/Pytorch-Video-Classification"<Pytorch-Video-Classification@noreply.github.com>; 抄送: "≮訫@煉冷≯"<1069842319@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [Yidadaa/Pytorch-Video-Classification] 请问这份代码准确率能达到多少呢？ (#1) @Zhangzhiwei1995 在 github 讨论吧，这样可以帮助到更多的人，建议把完整的报错信息贴上来。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

D:\Anaconda3\envs\pytorch37\python.exe E:/Pytorch-Video-Classification-master/train.py
Building dataset: 100%|██████████| 1048575/1048575 [00:03<00:00, 334129.70it/s]
Building dataset: 100%|██████████| 519386/519386 [00:01<00:00, 347466.06it/s]
Size of Training Set:  38322
Traceback (most recent call last):
  File "E:/Pytorch-Video-Classification-master/train.py", line 181, in <module>
    train_on_epochs(dataloaders['train'], dataloaders['test'], args.restore_from)
  File "E:/Pytorch-Video-Classification-master/train.py", line 67, in train_on_epochs
    train_losses, train_scores = train(model, train_loader, optimizer, ep, device)
  File "E:/Pytorch-Video-Classification-master/train.py", line 103, in train
    for i, (X, y) in enumerate(dataloader):
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\collate.py", line 80, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\collate.py", line 80, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\collate.py", line 54, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <torch_16672_2691369534>, error code: <1455>


Process finished with exit code 1

这是运行train.py全部的信息  不知道怎么解决  大佬求帮助
