### ISSUE TITLE
我在UCF101下训练的时候出现了一个问题

### ISSUE THREAD

**Issue by Zhangzhiwei1995** [Yidadaa/Pytorch-Video-Classification#2]
我在Windows10下pytorch1.2 torchvision0.4 显卡GTX1660Ti  显卡驱动cuda10 
我是在先运行  make_train_test.py 再运行train.py的时候出现了这样的问题。。

D:\Anaconda3\envs\pytorch37\python.exe E:/Pytorch-Video-Classification-master/train.py
Building dataset: 100%|██████████| 1048575/1048575 [00:03<00:00, 334129.70it/s]
Building dataset: 100%|██████████| 519386/519386 [00:01<00:00, 347466.06it/s]
Size of Training Set:  38322
Traceback (most recent call last):
  File "E:/Pytorch-Video-Classification-master/train.py", line 181, in <module>
    train_on_epochs(dataloaders['train'], dataloaders['test'], args.restore_from)
  File "E:/Pytorch-Video-Classification-master/train.py", line 67, in train_on_epochs
    train_losses, train_scores = train(model, train_loader, optimizer, ep, device)
  File "E:/Pytorch-Video-Classification-master/train.py", line 103, in train
    for i, (X, y) in enumerate(dataloader):
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\collate.py", line 80, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\collate.py", line 80, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\utils\data\_utils\collate.py", line 54, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\storage.py", line 128, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't open shared file mapping: <torch_16672_2691369534>, error code: <1455>
Process finished with exit code 1

**Comment by Yidadaa** [comment]
很抱歉回复晚了，关于你的问题，只找到一个相关的 issue：https://github.com/pytorch/pytorch/issues/18797 ，看起来像是读数据的时候出了问题，下面提供几个解决方法，请逐个尝试：

1. 修改`config.py`文件中`dataset_params`，调整为：`batch_size: 24, num_workers: 1, pin_memory: False`，此举是为了排除显卡内存不足以及多线程加载数据带来的隐患；
https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/config.py#L4-L9

2. 注释掉`train.py`文件中下列行，排除并行训练带来的隐患。
https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/train.py#L29-L33

**Comment by Zhangzhiwei1995** [comment]
> 很抱歉回复晚了，关于你的问题，只找到一个相关的 issue：[pytorch/pytorch#18797](https://github.com/pytorch/pytorch/issues/18797) ，看起来像是读数据的时候出了问题，下面提供几个解决方法，请逐个尝试：
> 
> 1. 修改`config.py`文件中`dataset_params`，调整为：`batch_size: 24, num_workers: 1, pin_memory: False`，此举是为了排除显卡内存不足以及多线程加载数据带来的隐患；
>    https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/config.py#L4-L9
> 2. 注释掉`train.py`文件中下列行，排除并行训练带来的隐患。
>    https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/train.py#L29-L33

特别感谢大佬的回复  我尝试一下看看效果。谢谢

**Comment by Zhangzhiwei1995** [comment]
大佬  我在修改完之后运行出现了这样的问题，查网上说是索引的问题，不知道是不是标签索引的问题。大佬能不能针对代码提供下解决办法  谢谢谢谢

D:\Anaconda3\envs\pytorch37\python.exe E:/Pytorch-Video-Classification-master/train.py
Building dataset: 100%|██████████| 1048575/1048575 [00:03<00:00, 325496.09it/s]
Building dataset: 100%|██████████| 519386/519386 [00:01<00:00, 340012.39it/s]
Size of Training Set:  38322
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [14,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [16,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [17,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [18,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [19,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [20,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [21,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/windows/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: block: [0,0,0], thread: [23,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu line=26 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "E:/Pytorch-Video-Classification-master/train.py", line 182, in <module>
    train_on_epochs(dataloaders['train'], dataloaders['test'], args.restore_from)
  File "E:/Pytorch-Video-Classification-master/train.py", line 68, in train_on_epochs
    train_losses, train_scores = train(model, train_loader, optimizer, ep, device)
  File "E:/Pytorch-Video-Classification-master/train.py", line 116, in train
    loss.backward()
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\Anaconda3\envs\pytorch37\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:26

Process finished with exit code 1

**Comment by Zhangzhiwei1995** [comment]
大佬  有空的话再看下GitHub，出现了一个新的问题 
好像是标签索引溢出了  大佬能不能针对代码提供一个解决方案呢  谢谢


------------------ 原始邮件 ------------------
发件人: "Yifei Zhang"<notifications@github.com>;
发送时间: 2019年10月17日(星期四) 上午10:37
收件人: "Yidadaa/Pytorch-Video-Classification"<Pytorch-Video-Classification@noreply.github.com>;
抄送: "≮訫@煉冷≯"<1069842319@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Yidadaa/Pytorch-Video-Classification] 我在UCF101下训练的时候出现了一个问题 (#2)




很抱歉回复晚了，关于你的问题，只找到一个相关的 issue：pytorch/pytorch#18797 ，看起来像是读数据的时候出了问题，下面提供几个解决方法，请逐个尝试：
  
 
修改config.py文件中dataset_params，调整为：batch_size: 24, num_workers: 1, pin_memory: False，此举是为了排除显卡内存不足以及多线程加载数据带来的隐患；
 https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/config.py#L4-L9
 
 
 
注释掉train.py文件中下列行，排除并行训练带来的隐患。
 https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/train.py#L29-L33

**Comment by Yidadaa** [comment]
修改这里的`num_classes`，跟你的数据集中类别数保持一致，我之前为了节省时间只跑了10类的。
https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/config.py#L22

**Comment by Zhangzhiwei1995** [comment]
嗯嗯  我看到了  有2处需要修改  谢谢




------------------ 原始邮件 ------------------
发件人: "Yifei Zhang"<notifications@github.com>;
发送时间: 2019年10月17日(星期四) 下午4:21
收件人: "Yidadaa/Pytorch-Video-Classification"<Pytorch-Video-Classification@noreply.github.com>;
抄送: "≮訫@煉冷≯"<1069842319@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Yidadaa/Pytorch-Video-Classification] 我在UCF101下训练的时候出现了一个问题 (#2)




修改这里的num_classes，跟你的数据集中类别数保持一致，我之前为了节省时间只跑了10类的。
 https://github.com/Yidadaa/Pytorch-Video-Classification/blob/af8131aa5f0420d5dcdfe4f59bb0b7489de9b6b3/config.py#L22
